name: 春风转
on:
  workflow_dispatch:
  schedule:
    - cron: '15 13 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/x101013416/123.git ~/123
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/123
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      - name: '【春风转】'
        run: |
          cd ~/123
          node Task/cfz.js
