name: 云扫码

on:
  workflow_dispatch:
  schedule:
     - cron: '35 2-14 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YSM_URL: ${{ secrets.YSM_URL }}
        YSM_HD: ${{ secrets.YSM_HD }}
        YSM_BD: ${{ secrets.YSM_BD }}
        YSM2_BD: ${{ secrets.YSM2_BD }}
        YSM_TX: ${{ secrets.YSM_TX }}		
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/x101013416/123.git ~/123
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.YSM_URL
        run: |
          cd ~/123
          npm install
      - name: '运行 【云扫码】'
        if: env.YSM_URL
        run: |
          cd ~/123
          node Task/ysm.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
