name: 阅友小说

on:
  workflow_dispatch:
  schedule:
     - cron: '*/15 0-15 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YYXSXXURL: ${{ secrets.YYXSXXURL }}
        YYXSSPURL: ${{ secrets.YYXSSPURL }}
        YYXSSPHD: ${{ secrets.YYXSSPHD }}
        YYXSSPBODY: ${{ secrets.YYXSSPBODY }}
        YYXSJSURL: ${{ secrets.YYXSJSURL }}
        YYXSSCURL: ${{ secrets.YYXSSCURL }}
        YYXSSCHD: ${{ secrets.YYXSSCHD }}
        YYXSCJURL: ${{ secrets.YYXSCJURL }}
        YYXSCJHD: ${{ secrets.YYXSCJHD }}  		
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/x101013416/123.git ~/123
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.YYXSSPHDL
        run: |
          cd ~/123
          npm install
      - name: '运行 【友小说】'
        if: env.YYXSSPHD
        run: |
          cd ~/123
          node Task/yyxs.js
        env: 
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
